## YAML Template.
---
app:
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
    url: http://localhost:1979/

email-services:
  from:
    email: saden1@gmail.com
    personal: Sharmarke Aden
  reply:
    email: saden1@gmail.com
    personal: Sharmarke Aden
  mandrill:
    username: saden1@gmail.com
    password: 84vw4p_chEGrcuL6m-s3TQ
    smtp:
        mail.smtp.host: smtp.mandrillapp.com
        mail.smtp.port: 587
        mail.smtp.auth: yes
        mail.smtp.starttls.enable: yes
        mail.smtp.starttls.required: yes
        mail.debug: yes
  mailgun:
    username: postmaster@sandbox12cf9fbe6d314143999e084b3f144131.mailgun.org
    password: 4fe601b230fd4c9c2f8f88db2300277a
    smtp:
        mail.smtp.host: smtp.mailgun.org
        mail.smtp.port: 587
        mail.smtp.auth: yes
        mail.smtp.starttls.enable: yes
        mail.smtp.starttls.required: yes
        mail.debug: yes